[package]
name = "google-cloud-longrunning"
version = "0.4.0"
authors = ["yoshidan <naohiro.y@gmail.com>"]
edition = "2021"
repository = "https://github.com/yoshidan/google-cloud-rust/tree/main/foundation/longrunning"
keywords = ["gcp","longrunning","googleapis","google-cloud-rust"]
license = "MIT"
readme = "README.md"
description = "Google Cloud Platform longrunning library."

[dependencies]
google-cloud-googleapis = { version = "0.4.0", path = "../../googleapis" }
google-cloud-gax = { version = "0.5.0", path = "../gax" }
tonic = { version = "0.6", features = ["tls", "prost"] }
prost = "0.9"
prost-types = "0.9"
