[package]
name = "google-cloud-longrunning"
version = "0.13.1"
authors = ["yoshidan <naohiro.y@gmail.com>"]
edition = "2021"
repository = "https://github.com/yoshidan/google-cloud-rust/tree/main/foundation/longrunning"
keywords = ["gcp","longrunning","googleapis","google-cloud-rust"]
license = "MIT"
readme = "README.md"
description = "Google Cloud Platform longrunning library."

[dependencies]
google-cloud-googleapis = { version = "0.8.0", path = "../../googleapis" }
google-cloud-gax = { version = "0.14.1", path = "../gax" }
tonic = { version = "0.8", features = ["tls", "prost"] }
prost = "0.11"
