[package]
name = "google-cloud-metadata"
version = "0.1.2"
authors = ["yoshidan <naohiro.y@gmail.com>"]
edition = "2021"
repository = "https://github.com/yoshidan/google-cloud-rust/tree/main/foundation/metadata"
keywords = ["gcp","googleapis","google-cloud-rust"]
license = "MIT"
readme = "README.md"
description = "Google Cloud Platform rust client."

[dependencies]
tokio = { version = "1.7", features = ["sync","net","parking_lot"] }
hyper = { version = "0.14", features = ["full"] }
thiserror = "1.0"

[dev-dependencies]
tokio = { version = "1.7", features = ["test-util", "rt-multi-thread", "macros"]}