[package]
name = "google-cloud-gax"
version = "0.8.0"
authors = ["yoshidan <naohiro.y@gmail.com>"]
edition = "2018"
repository = "https://github.com/yoshidan/google-cloud-rust/tree/main/foundation/gax"
keywords = ["gcp","googleapis","google-cloud-rust"]
license = "MIT"
readme = "README.md"
description = "Google Cloud Platform gRPC retry library."

[dependencies]
tracing = "0.1"
rand = "0.8"
tokio = { version = "1.17" }
tonic = { version = "0.7", features = ["tls", "prost", "tls-roots"] }
thiserror = "1.0"
tower = { version = "0.4", features = ["filter"] }
http = "0.2"
prost-types = "0.10"
google-cloud-auth= { version = "0.4.0", path = "../auth" }
tokio-util = "0.7"
tokio-retry = "0.3"