[package]
name = "google-cloud-gax"
version = "0.4.0"
authors = ["yoshidan <naohiro.y@gmail.com>"]
edition = "2018"
repository = "https://github.com/yoshidan/google-cloud-rust/tree/main/foundation/gax"
keywords = ["gcp","googleapis","google-cloud-rust"]
license = "MIT"
readme = "README.md"
description = "Google Cloud Platform gRPC retry library."

[dependencies]
log = "0.4"
rand = "0.8"
tokio = { version = "1.7" }
tonic = { version = "0.6", features = ["tls", "prost"] }
thiserror = "1.0"
tower = { version = "0.4" }
http = "0.2"
prost = "0.9"
prost-types = "0.9"
google-cloud-auth= { version = "0.1.2", path = "../auth" }
google-cloud-googleapis = { version = "0.3.0", path = "../../googleapis" }
tokio-util = "0.6"
tokio-retry = "0.3"