[package]
name = "google-cloud-spanner"
version = "0.3.0"
authors = ["yoshidan <naohiro.y@gmail.com>"]
edition = "2021"
repository = "https://github.com/yoshidan/google-cloud-rust/tree/main/spanner"
keywords = ["gcp","spanner","googleapis","google-cloud-rust"]
license-file = "LICENSE"
readme = "README.md"
description = "Google Cloud Platform spanner client library."
documentation = "https://docs.rs/google-cloud-spanner/0.3.0/google-cloud-spanner/"

[dependencies]
log = "0.4"
tonic = { version = "0.6", features = ["tls", "prost"] }
prost = "0.9"
prost-types = "0.9"
tokio = { version = "1.7", features = ["full"] }
chrono = "0.4"
thiserror = "1.0"
async-trait = "0.1"
rust_decimal = "1.15"
parking_lot = "0.11"
base64 = "0.13"
anyhow = "1.0"

google-cloud-longrunning= { version = "0.2.0", path = "../foundation/longrunning" }
google-cloud-grpc = { version = "0.2.0", path = "../foundation/grpc" }
google-cloud-gax = { version = "0.2.0", path = "../foundation/gax" }
google-cloud-googleapis = { version = "0.2.0", path = "../googleapis" }

[dev-dependencies]
env_logger = "0.9"
serial_test = "0.5.1"
anyhow = "1.0.48"
