[package]
name = "google-cloud-spanner"
version = "0.1.0"
authors = ["yoshidan <naohiro.y@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4.0"
tonic = { version = "0.5", features = ["tls", "prost"] }
prost = "0.8"
prost-types = "0.8"
hyper = { version = "0.14", features = ["full"] }
hyper-tls = "0.5"
tokio = { version = "1.7", features = ["full"] }
chrono = "0.4"
thiserror = "1.0"
async-trait = "0.1"
home = "0.5"
rust_decimal = "1.15"
parking_lot = "0.11"
futures-util = "0.3"
futures-channel = "0.3"
base64 = "0.13"

google-cloud-auth = { path = "../auth" }
google-cloud-gax = { path = "../gax" }
google-cloud-googleapis = { path = "../googleapis" }

[dev-dependencies]
env_logger = "0.9"
serial_test = "*"