[package]
name = "google-cloud-spanner"
version = "0.11.0"
authors = ["yoshidan <naohiro.y@gmail.com>"]
edition = "2021"
repository = "https://github.com/yoshidan/google-cloud-rust/tree/main/spanner"
keywords = ["gcp","spanner","googleapis","google-cloud-rust"]
license = "MIT"
readme = "README.md"
description = "Google Cloud Platform spanner client library."
documentation = "https://docs.rs/google-cloud-spanner/latest/google_cloud_spanner/"

[dependencies]
tracing = "0.1"
prost-types = "0.11"
tokio = "1.20"
chrono = "0.4"
thiserror = "1.0"
async-trait = "0.1"
parking_lot = "0.12"
base64 = "0.13"
anyhow = "1.0"

google-cloud-auth= {  version = "0.5.0", path = "../foundation/auth", default-features = false}
google-cloud-longrunning= { version = "0.8.0", path = "../foundation/longrunning", default-features = false}
google-cloud-gax = { version = "0.9.0", path = "../foundation/gax", default-features = false}
google-cloud-googleapis = { version = "0.6.0", path = "../googleapis", features = ["spanner"]}

[dev-dependencies]
tokio = { version="1.20", features=["rt-multi-thread"] }
tracing-subscriber = "0.3"
serial_test = "0.9"
anyhow = "1.0.48"
ctor = "0.1"

[features]
default = ["default-tls"]
default-tls = ["google-cloud-auth/default-tls", "google-cloud-gax/default-tls", "google-cloud-longrunning/default-tls"]
rustls-tls = ["google-cloud-auth/rustls-tls", "google-cloud-gax/rustls-tls", "google-cloud-longrunning/rustls-tls"]
trace = []
