[package]
name = "google-cloud-spanner"
version = "0.7.0"
authors = ["yoshidan <naohiro.y@gmail.com>"]
edition = "2021"
repository = "https://github.com/yoshidan/google-cloud-rust/tree/main/spanner"
keywords = ["gcp","spanner","googleapis","google-cloud-rust"]
license = "MIT"
readme = "README.md"
description = "Google Cloud Platform spanner client library."
documentation = "https://docs.rs/google-cloud-spanner/0.7.0/google-cloud-spanner/"

[dependencies]
tracing = "0.1"
prost = "0.9"
prost-types = "0.9"
tokio = "1.17"
chrono = "0.4"
thiserror = "1.0"
async-trait = "0.1"
parking_lot = "0.11"
base64 = "0.13"
anyhow = "1.0"

google-cloud-longrunning= { version = "0.4.0", path = "../foundation/longrunning" }
google-cloud-gax = { version = "0.5.0", path = "../foundation/gax" }
google-cloud-googleapis = { version = "0.4.0", path = "../googleapis", features = ["spanner"]}

[dev-dependencies]
tokio = { version="1.17", features=["rt-multi-thread"] }
tracing-subscriber = "0.3"
serial_test = "0.5.1"
anyhow = "1.0.48"
ctor = "0.1"
