[package]
name = "google-cloud-spanner"
version = "0.18.1"
authors = ["yoshidan <naohiro.y@gmail.com>"]
edition = "2021"
repository = "https://github.com/yoshidan/google-cloud-rust/tree/main/spanner"
keywords = ["gcp","spanner","googleapis","google-cloud-rust"]
license = "MIT"
readme = "README.md"
description = "Google Cloud Platform spanner client library."
documentation = "https://docs.rs/google-cloud-spanner/latest/google_cloud_spanner/"

[dependencies]
tracing = "0.1"
prost-types = "0.11"
tokio = "1.20"
time = { version="0.3", features = ["std", "macros", "formatting", "parsing"] }
thiserror = "1.0"
async-trait = "0.1"
parking_lot = "0.12"
base64 = "0.21"
serde = { version = "1.0", optional = true, features = ["derive"] }
tokio-util = "0.7"

google-cloud-token = { version = "0.1.1", path = "../foundation/token" }
google-cloud-longrunning= { version = "0.13.1", path = "../foundation/longrunning" }
google-cloud-gax = { version = "0.14.1", path = "../foundation/gax" }
google-cloud-googleapis = { version = "0.8.0", path = "../googleapis", features = ["spanner"]}

[dev-dependencies]
tokio = { version="1.20", features=["rt-multi-thread"] }
tracing-subscriber = { version="0.3", features=["env-filter"] }
serial_test = "0.9"
ctor = "0.1"

[features]
default = ["serde"]
trace = []
