[workspace]
members = [
    "foundation/token",
    "foundation/metadata",
    "foundation/gax",
    "foundation/longrunning",
    "foundation/auth",
    "googleapis",
    "spanner",
    "pubsub",
    "storage",
    "spanner-derive"
]