[package]
name = "google-cloud-storage"
version = "0.4.2"
edition = "2021"
authors = ["yoshidan <naohiro.y@gmail.com>"]
repository = "https://github.com/yoshidan/google-cloud-rust/tree/main/storage"
keywords = ["gcp","gcs","storage","googleapis","google-cloud-rust"]
license = "MIT"
readme = "README.md"
description = "Google Cloud Platform storage client library."
documentation = "https://docs.rs/google-cloud-storage/latest/google_cloud_storage/"

[dependencies]
google-cloud-auth = { version = "0.4.2", path = "../foundation/auth", default-features = false }
google-cloud-metadata = { version = "0.3.1", path = "../foundation/metadata", default-features = false }
rsa = "0.6"
thiserror = "1.0"
chrono = { version = "0.4", features=["serde"]}
base64 = "0.13"
regex = "1.6"
sha2 = "0.10"
base16ct = "0.1"
ring = "0.17.0-alpha.11"
tokio = { version="1.20", features=["macros"] }
async-stream = "0.3"
once_cell = "1.13"
hex = "0.4.3"
url = "2.2.2"
tracing = "0.1"
reqwest = { version = "0.11", features = ["json", "stream"], default-features = false }
serde = "1.0"
serde_json = "1.0"
tokio-util = "0.7"
percent-encoding = "2.1"
futures-util = "0.3"
bytes = "1.2"

[dev-dependencies]
tokio = { version="1.20", features=["rt-multi-thread"] }
serial_test = "0.9"
tracing-subscriber = "0.3.11"
ctor = "0.1.22"
tokio-util =  {version ="0.7", features = ["codec"] }

[features]
default = ["default-tls"]
default-tls = ["reqwest/default-tls", "google-cloud-auth/default-tls", "google-cloud-metadata/default-tls"]
rustls-tls = ["reqwest/rustls-tls", "google-cloud-auth/rustls-tls", "google-cloud-metadata/rustls-tls"]
trace = []
